'use strict';

// ============================================================================
// document-service
// ----------------------------------------------------------------------------
// Simulates document intake/processing for a case (validating an uploaded
// attachment, listing processed documents). The gateway calls this during
// case creation (validate) and case detail (list).
//
// This is where the CPU-bound work lives. It always does a little real work
// (a checksum over generated bytes). Under the HIGH_CPU scenario it runs an
// additional busy-loop for `intensity` ms PER REQUEST, raising process CPU and
// its own response time.
// ============================================================================

const crypto = require('crypto');
const express = require('express');
const morgan = require('morgan');
const { Pool } = require('pg');

const PORT = parseInt(process.env.PORT || '3002', 10);
const FLAG_TTL_MS = parseInt(process.env.FLAG_TTL_MS || '2000', 10);

const pool = new Pool({
  host: process.env.PGHOST || 'postgres',
  port: parseInt(process.env.PGPORT || '5432', 10),
  user: process.env.PGUSER || 'casemgmt',
  password: process.env.PGPASSWORD || 'casemgmt',
  database: process.env.PGDATABASE || 'casemgmt',
  max: parseInt(process.env.PG_POOL_MAX || '5', 10)
});

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// --- Scenario flags (shared table, short TTL cache) ------------------------
const DEFAULT_FLAGS = {
  HIGH_CPU: { enabled: false, intensity: 0 },
  DB_FAILURE_RATE: { enabled: false, intensity: 0 },
  BACKEND_SLOWDOWN: { enabled: false, intensity: 0 }
};
let flagCache = { at: 0, data: DEFAULT_FLAGS };

async function getFlags() {
  const now = Date.now();
  if (now - flagCache.at < FLAG_TTL_MS) return flagCache.data;
  try {
    const { rows } = await pool.query('SELECT name, enabled, intensity FROM scenario_flags');
    const data = {};
    for (const r of rows) data[r.name] = { enabled: r.enabled, intensity: r.intensity };
    flagCache = { at: now, data };
    return data;
  } catch (err) {
    return flagCache.data;
  }
}

// Tight CPU loop that cannot be optimised away (feeds a rolling hash). Burns
// the calling thread for `ms` milliseconds — exactly what HIGH_CPU needs.
function burnCpu(ms) {
  const deadline = Date.now() + ms;
  let acc = crypto.createHash('sha256').update('seed').digest('hex');
  let iterations = 0;
  while (Date.now() < deadline) {
    for (let i = 0; i < 5000; i++) {
      acc = crypto.createHash('sha256').update(acc + i).digest('hex');
      iterations++;
    }
  }
  return iterations;
}

async function maybeBurnCpu() {
  const f = (await getFlags()).HIGH_CPU;
  if (f && f.enabled && f.intensity > 0) return burnCpu(f.intensity);
  return 0;
}

// Baseline document work: hash a small generated payload (always runs).
function checksum(seed) {
  const buf = crypto.randomBytes(64 * 1024); // 64 KB "page image"
  return crypto.createHash('sha256').update(buf).update(String(seed)).digest('hex').slice(0, 16);
}

// --- App -------------------------------------------------------------------
const app = express();
app.use(express.json());
app.use(morgan('combined'));

app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'document-service' }));

// Validate an uploaded attachment for a case (called during case creation).
app.post('/documents/validate', async (req, res, next) => {
  try {
    const burned = await maybeBurnCpu();
    const fileName = (req.body && req.body.fileName) || 'attachment.pdf';
    const pages = 1 + Math.floor(Math.random() * 12);
    const sum = checksum(fileName);
    res.json({
      fileName,
      valid: true,
      pages,
      sizeKb: pages * 64,
      checksum: sum,
      mimeType: 'application/pdf',
      cpuIterations: burned,
      processedAt: new Date().toISOString()
    });
  } catch (err) {
    next(err);
  }
});

// List the processed documents attached to a case (called on case detail).
app.get('/documents/case/:id', async (req, res, next) => {
  try {
    const burned = await maybeBurnCpu();
    const id = parseInt(req.params.id, 10) || 0;
    const kinds = ['Application Form', 'Proof of Identity', 'Supporting Statement', 'Income Verification'];
    const count = 1 + (id % 4);
    const documents = [];
    for (let i = 0; i < count; i++) {
      documents.push({
        name: `${kinds[(id + i) % kinds.length]}.pdf`,
        pages: 1 + ((id + i) % 8),
        status: 'Processed',
        checksum: checksum(`${id}-${i}`)
      });
    }
    res.json({ caseId: id, documents, cpuIterations: burned });
  } catch (err) {
    next(err);
  }
});

app.use((err, _req, res, _next) => {
  console.error('[document-service] request failed:', err.message);
  res.status(500).json({ error: 'document-service internal error', detail: err.message });
});

async function waitForDb(retries = 30) {
  for (let i = 1; i <= retries; i++) {
    try {
      await pool.query('SELECT 1');
      console.log('[document-service] connected to Postgres');
      return;
    } catch (err) {
      console.log(`[document-service] waiting for Postgres (${i}/${retries}): ${err.message}`);
      await sleep(2000);
    }
  }
  // Document-service can still serve CPU work without the DB; warn and continue.
  console.warn('[document-service] proceeding without confirmed DB connection');
}

waitForDb().then(() =>
  app.listen(PORT, () => console.log(`[document-service] listening on :${PORT}`))
);
